import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";

export default function Home() {
  var [size, setSize] = useState<number>(0);

  async function callAPI(type: "imageFile" | "fontFile") {
    await fetch(`/api/sizeCheckAPI/${type}`)
      .then((res) => res.json())
      .then((data) => {
        setSize(data);
      });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>
          <h1>File Path Server Check </h1>
          <br></br>
          <button onClick={() => callAPI("imageFile")}>
            Check Image File Size From Server Side
          </button>
          <br></br>
          <br></br>
          <button onClick={() => callAPI("fontFile")}>
            Check Font File Size From Server Side
          </button>
          <br></br>
          <br></br>
          <p>Size of File Found on Server: {size}</p>
        </>
      </main>
    </>
  );
}
